//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<double> payroll { get; set; }
        public string badge { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> vacationHours { get; set; }
        public Nullable<int> PersonalTimeOff { get; set; }
        public Nullable<int> HourlyRates { get; set; }
        public string Notes { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
